/**
 * src/core/contracts/ai.ts — TypeScript mirror of contracts/ai/models.py (M2.2)
 *
 * These interfaces are the canonical wire types for the AI execution pipeline.
 * They MUST remain structurally equivalent to the Pydantic models in
 * contracts/ai/models.py.  Any change to the Python models must be reflected
 * here (enforced by tests/test_contract_sync.py).
 *
 * Name Disambiguation (M2.1)
 * --------------------------
 * Each type carries the `Contract` suffix to avoid shadowing:
 *   ExecutionPlanContract    ≠  engine/scalability.py:ExecutionPlan
 *   ExecutionContextContract ≠  src/core/types.ts:ExecutionContext
 *   ValidationResultContract ≠  digital_twin/validation_gateway.py:ValidationResult
 *   StudyResultContract      ≠  core_model/specs.py:StudyResult
 */

// ---------------------------------------------------------------------------
// Enumerations (mirror Python Enum values)
// ---------------------------------------------------------------------------

export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'bypassed';

export type NodeStatus = 'queued' | 'running' | 'completed' | 'failed' | 'skipped';

// ---------------------------------------------------------------------------
// 1. ProvenanceContract
// ---------------------------------------------------------------------------

export interface ProvenanceContract {
  /** Origin of the value: 'user_input', 'computed', 'project_data', or 'standard'. */
  source: string;
  /** Specific reference, e.g. 'IEC 60909:2016 §4.3.1' or task_id. */
  ref: string;
  /** Confidence level 0.0–1.0; 1.0 = deterministic engine output. */
  confidence: number;
  /** ISO-8601 UTC timestamp when the value was produced. */
  computed_at: string;
}

// ---------------------------------------------------------------------------
// 2. EvidenceContract
// ---------------------------------------------------------------------------

export interface EvidenceContract {
  /** Short label identifying this evidence item. */
  key: string;
  /** The evidence value (numeric, string, or nested object). */
  value: unknown;
  /** Traceability chain for this evidence item. */
  provenance: ProvenanceContract;
  /** Normative clause (e.g. 'IEC 60909:2016 §4.3') governing this value. */
  standard_clause: string;
}

// ---------------------------------------------------------------------------
// 3. PlanNodeContract
// ---------------------------------------------------------------------------

export interface PlanNodeContract {
  /** Unique identifier for this plan node. */
  node_id: string;
  /** Canonical study type key (ADR-0001). */
  study_type: string;
  /** Target agent id from AGENT_REGISTRY. */
  agent_id: string;
  /** List of node_ids that must complete before this node runs. */
  depends_on: string[];
  /** Study parameters passed to the agent. */
  parameters: Record<string, unknown>;
  status: NodeStatus;
  /** Evidence items supporting parameters (fail-closed requirement). */
  evidence: EvidenceContract[];
  /** Mapping from upstream output keys to this node's parameter keys (M3.2/M3.3). */
  input_mapping?: Record<string, string>;
  /** Mapping from this node's output keys to downstream input keys (M3.2/M3.3). */
  output_mapping?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// 4. ExecutionPlanContract — disambiguates engine/scalability.py:ExecutionPlan
// ---------------------------------------------------------------------------

export interface ExecutionPlanContract {
  /** Globally unique plan identifier (UUID-4). */
  plan_id: string;
  /** Parent run identifier (UUID-4). */
  run_id: string;
  /** Ordered list of plan nodes. */
  nodes: PlanNodeContract[];
  created_at: string;
  description: string;
  /** Topological sort of node_ids; empty means sequential execution. */
  topological_order: string[];
}

// ---------------------------------------------------------------------------
// 5. ExecutionContextContract — disambiguates src/core/types.ts:ExecutionContext
// ---------------------------------------------------------------------------

export interface ExecutionContextContract {
  /** Tenant identifier for multi-tenant isolation. */
  tenant_id: string;
  /** Authenticated user identifier. */
  user_id: string;
  session_id: string;
  trace_id: string;
  /** If true, external LLM calls are blocked (PRIVACY_MODE_ACTIVE). */
  privacy_mode: boolean;
  /** Provenance source label for fail-closed enforcement. */
  source: string;
}

// ---------------------------------------------------------------------------
// 6. ExecutionRequestContract
// ---------------------------------------------------------------------------

export interface ExecutionRequestContract {
  /** Unique run identifier (UUID-4), generated by caller. */
  run_id: string;
  plan: ExecutionPlanContract;
  context: ExecutionContextContract;
  requested_at: string;
  /** If true, validate and plan but do not execute any studies. */
  dry_run: boolean;
}

// ---------------------------------------------------------------------------
// 7. ValidationResultContract — disambiguates digital_twin:ValidationResult
// ---------------------------------------------------------------------------

export interface ValidationResultContract {
  check_name: string;
  passed: boolean;
  severity: string;
  message: string;
  details: Record<string, unknown>;
  checked_at: string;
}

// ---------------------------------------------------------------------------
// 8. StudyResultContract — disambiguates core_model.specs.StudyResult
// ---------------------------------------------------------------------------

export interface StudyResultContract {
  /** Parent run identifier. */
  run_id: string;
  /** Parent plan identifier. */
  plan_id: string;
  /** Plan node that produced this result. */
  node_id: string;
  /** Canonical study type key (ADR-0001). */
  study_type: string;
  /** Agent that executed this node. */
  agent_id: string;
  success: boolean;
  data: Record<string, unknown>;
  warnings: string[];
  errors: string[];
  /** Supporting evidence for computed values (IEEE 1584-2018 §5). */
  evidence: EvidenceContract[];
  execution_time_sec: number;
  completed_at: string;
}

// ---------------------------------------------------------------------------
// 9. ApprovalStateContract
// ---------------------------------------------------------------------------

export interface ApprovalStateContract {
  /** Unique identifier for the action requiring approval. */
  action_id: string;
  /** User who initiated (made) the action. */
  maker_id: string;
  /** User who approved or rejected; null if still pending. */
  checker_id: string | null;
  status: ApprovalStatus;
  action_type: string;
  /** SHA-256 hash of the action payload for integrity verification. */
  payload_hash: string;
  created_at: string;
  decided_at: string | null;
  reason: string;
}

// ---------------------------------------------------------------------------
// 10. ExecutionTraceContract
// ---------------------------------------------------------------------------

export interface ExecutionTraceContract {
  /** Run identifier (matches ExecutionRequestContract.run_id). */
  run_id: string;
  plan_id: string;
  context: ExecutionContextContract;
  /** Results for each executed plan node, in completion order. */
  node_results: StudyResultContract[];
  /** Contract and registry validations run before/after execution. */
  validations: ValidationResultContract[];
  /** Maker-checker approval state if the run required dual control. */
  approval: ApprovalStateContract | null;
  started_at: string;
  completed_at: string | null;
  total_execution_time_sec: number;
  overall_success: boolean;
  /** Langfuse observability URL for this run (empty if tracing disabled). */
  langfuse_trace_url: string;
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

export function isStudyResultContract(obj: unknown): obj is StudyResultContract {
  if (typeof obj !== 'object' || obj === null) return false;
  const r = obj as Record<string, unknown>;
  return (
    typeof r['run_id'] === 'string' &&
    typeof r['plan_id'] === 'string' &&
    typeof r['node_id'] === 'string' &&
    typeof r['study_type'] === 'string' &&
    typeof r['agent_id'] === 'string' &&
    typeof r['success'] === 'boolean'
  );
}

export function isExecutionRequestContract(obj: unknown): obj is ExecutionRequestContract {
  if (typeof obj !== 'object' || obj === null) return false;
  const r = obj as Record<string, unknown>;
  return (
    typeof r['run_id'] === 'string' &&
    typeof r['plan'] === 'object' &&
    typeof r['context'] === 'object'
  );
}
