version: 2
secret:
  ignored_paths:
    - 'scripts/seed_e2e_user.py'
    - 'testsprite_tests/**/*'
    - 'tests/**/*'
  ignored_matches:
    - name: 'e2e-test-generic-password'
      match: '54de7f606f2523cba8efac173fab42fb7f59d56ceff974c8fdb7342cf2cfe345'
