"""
msha_report.py — Generate MSHA-compliant report for mine fire protection.

V214: Generates a structured report per MSHA 30 CFR Part 75 + NFPA 120.
"""

from __future__ import annotations

from datetime import datetime, timezone

from fireai.mining.core.msha_compliance import MSHAComplianceReport


def generate_msha_report(
    report: MSHAComplianceReport,
    output_format: str = "markdown",
) -> str:
    """
    Generate an MSHA compliance report in the specified format.

    Args:
        report: MSHAComplianceReport from MSHAComplianceChecker.
        output_format: 'markdown' (default) or 'json'.

    Returns:
        Report as a string.
    """
    if output_format == "json":
        import json
        return json.dumps({
            "mine_name": report.mine_name,
            "section_name": report.section_name,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "overall_status": report.overall_status,
            "checks": [
                {
                    "rule_id": c.rule_id,
                    "standard": c.standard,
                    "description": c.description,
                    "status": c.status,
                    "details": c.details,
                    "remediation": c.remediation,
                }
                for c in report.checks
            ],
        }, indent=2, ensure_ascii=False)

    # Markdown format
    lines = [
        f"# MSHA Compliance Report — {report.mine_name}",
        f"**Section:** {report.section_name}",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Overall Status:** {report.overall_status}",
        "",
        "## Compliance Checks",
        "",
    ]

    for c in report.checks:
        lines.append(f"### {c.rule_id}: {c.description}")
        lines.append(f"- **Standard:** {c.standard}")
        lines.append(f"- **Status:** {c.status}")
        lines.append(f"- **Details:** {c.details}")
        if c.remediation:
            lines.append(f"- **Remediation:** {c.remediation}")
        lines.append("")

    # Summary
    pass_count = sum(1 for c in report.checks if c.status == "PASS")
    fail_count = sum(1 for c in report.checks if c.status == "FAIL")
    warn_count = sum(1 for c in report.checks if c.status == "WARNING")

    lines.extend([
        "## Summary",
        f"- **Passed:** {pass_count}",
        f"- **Warnings:** {warn_count}",
        f"- **Failed:** {fail_count}",
        f"- **Total checks:** {len(report.checks)}",
        "",
        "---",
        "This report was generated by FireAI / BAZSPARK mining module.",
        "All compliance checks are based on MSHA 30 CFR Part 75 + NFPA 120-2022.",
    ])

    return "\n".join(lines)
