apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etap-ai.fullname" . }}-secrets
  labels:
    {{- include "etap-ai.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.env.ENGINEERING_SERVICE_API_KEY | b64enc | quote }}
