apiVersion: v2
name: etap-ai
description: A Helm chart for ETAP-AI-WORK Engineering Service
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: ETAP-AI Team
    email: ahmdelbaz28@gmail.com
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/license: MIT