"""scripts/seed_components_generator.py — Generate validated seed data for Component Library."""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent / "data" / "components"

CABLES = [
    {
        "id": "cable-iec60364-cu-pvc-1kv-1c-25",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/PVC 1kV",
        "name": "1kV Single Core PVC Copper Cable 25mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-PVC-1X25",
        "specs": {
            "conductor_material": "copper",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 25,
            "resistance_ohm_per_km": 0.727,
            "reactance_ohm_per_km": 0.098,
            "current_rating_a": 130,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228", "IEC 60502-1"],
        "tags": ["lv-cable", "copper", "pvc", "single-core", "25mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-pvc-1kv-1c-50",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/PVC 1kV",
        "name": "1kV Single Core PVC Copper Cable 50mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-PVC-1X50",
        "specs": {
            "conductor_material": "copper",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 50,
            "resistance_ohm_per_km": 0.387,
            "reactance_ohm_per_km": 0.093,
            "current_rating_a": 195,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228", "IEC 60502-1"],
        "tags": ["lv-cable", "copper", "pvc", "single-core", "50mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-pvc-1kv-1c-95",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/PVC 1kV",
        "name": "1kV Single Core PVC Copper Cable 95mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-PVC-1X95",
        "specs": {
            "conductor_material": "copper",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 95,
            "resistance_ohm_per_km": 0.193,
            "reactance_ohm_per_km": 0.088,
            "current_rating_a": 290,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228", "IEC 60502-1"],
        "tags": ["lv-cable", "copper", "pvc", "single-core", "95mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-pvc-1kv-1c-150",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/PVC 1kV",
        "name": "1kV Single Core PVC Copper Cable 150mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-PVC-1X150",
        "specs": {
            "conductor_material": "copper",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 150,
            "resistance_ohm_per_km": 0.124,
            "reactance_ohm_per_km": 0.085,
            "current_rating_a": 380,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228", "IEC 60502-1"],
        "tags": ["lv-cable", "copper", "pvc", "single-core", "150mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-pvc-1kv-1c-240",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/PVC 1kV",
        "name": "1kV Single Core PVC Copper Cable 240mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-PVC-1X240",
        "specs": {
            "conductor_material": "copper",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 240,
            "resistance_ohm_per_km": 0.0754,
            "reactance_ohm_per_km": 0.082,
            "current_rating_a": 505,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228", "IEC 60502-1"],
        "tags": ["lv-cable", "copper", "pvc", "single-core", "240mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-al-pvc-1kv-1c-50",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "AL/PVC 1kV",
        "name": "1kV Single Core PVC Aluminum Cable 50mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-AL-PVC-1X50",
        "specs": {
            "conductor_material": "aluminum",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 50,
            "resistance_ohm_per_km": 0.641,
            "reactance_ohm_per_km": 0.093,
            "current_rating_a": 150,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228"],
        "tags": ["lv-cable", "aluminum", "pvc", "single-core", "50mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-al-pvc-1kv-1c-95",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "AL/PVC 1kV",
        "name": "1kV Single Core PVC Aluminum Cable 95mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-AL-PVC-1X95",
        "specs": {
            "conductor_material": "aluminum",
            "insulation": "pvc",
            "voltage_rating_kv": 1.0,
            "cores": 1,
            "cross_section_mm2": 95,
            "resistance_ohm_per_km": 0.320,
            "reactance_ohm_per_km": 0.088,
            "current_rating_a": 225,
            "max_operating_temp_c": 70,
        },
        "standards": ["IEC 60364-52", "IEC 60228"],
        "tags": ["lv-cable", "aluminum", "pvc", "single-core", "95mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-xlpe-11kv-3c-95",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/XLPE 11kV",
        "name": "11kV Three Core XLPE Copper Cable 95mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-XLPE-3X95-11KV",
        "specs": {
            "conductor_material": "copper",
            "insulation": "xlpe",
            "voltage_rating_kv": 11.0,
            "cores": 3,
            "cross_section_mm2": 95,
            "resistance_ohm_per_km": 0.193,
            "reactance_ohm_per_km": 0.108,
            "current_rating_a": 315,
            "max_operating_temp_c": 90,
        },
        "standards": ["IEC 60502-2", "IEC 60228", "IEC 60364"],
        "tags": ["mv-cable", "copper", "xlpe", "three-core", "11kv", "95mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-cu-xlpe-11kv-3c-150",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "CU/XLPE 11kV",
        "name": "11kV Three Core XLPE Copper Cable 150mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-CU-XLPE-3X150-11KV",
        "specs": {
            "conductor_material": "copper",
            "insulation": "xlpe",
            "voltage_rating_kv": 11.0,
            "cores": 3,
            "cross_section_mm2": 150,
            "resistance_ohm_per_km": 0.124,
            "reactance_ohm_per_km": 0.102,
            "current_rating_a": 405,
            "max_operating_temp_c": 90,
        },
        "standards": ["IEC 60502-2", "IEC 60228", "IEC 60364"],
        "tags": ["mv-cable", "copper", "xlpe", "three-core", "11kv", "150mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cable-iec60364-al-xlpe-11kv-3c-240",
        "type": "cable",
        "category": "IEC 60364",
        "subcategory": "AL/XLPE 11kV",
        "name": "11kV Three Core XLPE Aluminum Cable 240mm²",
        "manufacturer": "Generic Standard",
        "model_number": "IEC-AL-XLPE-3X240-11KV",
        "specs": {
            "conductor_material": "aluminum",
            "insulation": "xlpe",
            "voltage_rating_kv": 11.0,
            "cores": 3,
            "cross_section_mm2": 240,
            "resistance_ohm_per_km": 0.125,
            "reactance_ohm_per_km": 0.096,
            "current_rating_a": 435,
            "max_operating_temp_c": 90,
        },
        "standards": ["IEC 60502-2", "IEC 60228", "IEC 60364"],
        "tags": ["mv-cable", "aluminum", "xlpe", "three-core", "11kv", "240mm2"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
]

TRANSFORMERS = [
    {
        "id": "xfmr-ieee-c57-500kva-11-0415kv",
        "type": "transformer",
        "category": "IEEE C57",
        "subcategory": "Distribution Transformer",
        "name": "500 kVA Distribution Transformer 11/0.415 kV",
        "manufacturer": "Standard IEEE Class",
        "model_number": "C57-DIST-500KVA",
        "specs": {
            "rated_power_kva": 500,
            "primary_voltage_kv": 11.0,
            "secondary_voltage_kv": 0.415,
            "phases": 3,
            "frequency_hz": 50,
            "impedance_percent": 4.5,
            "xr_ratio": 4.5,
            "vector_group": "Dyn11",
            "no_load_loss_kw": 0.95,
            "full_load_loss_kw": 5.4,
            "cooling": "ONAN",
        },
        "standards": ["IEEE C57.12.00", "IEC 60076"],
        "tags": ["distribution-transformer", "500kva", "step-down", "11kv", "415v"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "xfmr-ieee-c57-1000kva-11-0415kv",
        "type": "transformer",
        "category": "IEEE C57",
        "subcategory": "Distribution Transformer",
        "name": "1000 kVA Distribution Transformer 11/0.415 kV",
        "manufacturer": "Standard IEEE Class",
        "model_number": "C57-DIST-1000KVA",
        "specs": {
            "rated_power_kva": 1000,
            "primary_voltage_kv": 11.0,
            "secondary_voltage_kv": 0.415,
            "phases": 3,
            "frequency_hz": 50,
            "impedance_percent": 5.0,
            "xr_ratio": 6.0,
            "vector_group": "Dyn11",
            "no_load_loss_kw": 1.6,
            "full_load_loss_kw": 10.5,
            "cooling": "ONAN",
        },
        "standards": ["IEEE C57.12.00", "IEC 60076"],
        "tags": ["distribution-transformer", "1000kva", "step-down", "11kv", "415v"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "xfmr-ieee-c57-2500kva-33-11kv",
        "type": "transformer",
        "category": "IEEE C57",
        "subcategory": "Substation Power Transformer",
        "name": "2.5 MVA Primary Substation Transformer 33/11 kV",
        "manufacturer": "Standard IEEE Class",
        "model_number": "C57-SUB-2500KVA",
        "specs": {
            "rated_power_kva": 2500,
            "primary_voltage_kv": 33.0,
            "secondary_voltage_kv": 11.0,
            "phases": 3,
            "frequency_hz": 50,
            "impedance_percent": 6.25,
            "xr_ratio": 8.5,
            "vector_group": "Dyn11",
            "no_load_loss_kw": 3.2,
            "full_load_loss_kw": 21.0,
            "cooling": "ONAN/ONAF",
        },
        "standards": ["IEEE C57.12.00", "IEC 60076"],
        "tags": ["power-transformer", "2500kva", "substation", "33kv", "11kv"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "xfmr-ieee-c57-5mva-33-11kv",
        "type": "transformer",
        "category": "IEEE C57",
        "subcategory": "Substation Power Transformer",
        "name": "5 MVA Primary Substation Transformer 33/11 kV",
        "manufacturer": "Standard IEEE Class",
        "model_number": "C57-SUB-5MVA",
        "specs": {
            "rated_power_kva": 5000,
            "primary_voltage_kv": 33.0,
            "secondary_voltage_kv": 11.0,
            "phases": 3,
            "frequency_hz": 50,
            "impedance_percent": 7.15,
            "xr_ratio": 11.0,
            "vector_group": "Dyn11",
            "no_load_loss_kw": 5.4,
            "full_load_loss_kw": 36.5,
            "cooling": "ONAN/ONAF",
        },
        "standards": ["IEEE C57.12.00", "IEC 60076"],
        "tags": ["power-transformer", "5mva", "substation", "33kv", "11kv"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "xfmr-ieee-c57-20mva-132-33kv",
        "type": "transformer",
        "category": "IEEE C57",
        "subcategory": "Transmission Grid Transformer",
        "name": "20 MVA Grid Intertie Transformer 132/33 kV",
        "manufacturer": "Standard IEEE Class",
        "model_number": "C57-GRID-20MVA",
        "specs": {
            "rated_power_kva": 20000,
            "primary_voltage_kv": 132.0,
            "secondary_voltage_kv": 33.0,
            "phases": 3,
            "frequency_hz": 50,
            "impedance_percent": 10.5,
            "xr_ratio": 18.0,
            "vector_group": "Ynd11",
            "no_load_loss_kw": 16.0,
            "full_load_loss_kw": 110.0,
            "cooling": "ONAN/ONAF/OFAF",
        },
        "standards": ["IEEE C57.12.00", "IEC 60076"],
        "tags": ["grid-transformer", "20mva", "transmission", "132kv", "33kv"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
]

BREAKERS = [
    {
        "id": "cb-iec62271-lv-acb-1600a-65ka",
        "type": "breaker",
        "category": "IEC 62271",
        "subcategory": "Low Voltage Air Circuit Breaker",
        "name": "LV Air Circuit Breaker 1600A 65kA",
        "manufacturer": "Standard IEC Class",
        "model_number": "ACB-1600-65",
        "specs": {
            "rated_voltage_kv": 0.69,
            "rated_current_a": 1600,
            "breaking_capacity_ka": 65.0,
            "making_capacity_ka": 143.0,
            "short_time_withstand_ka_1s": 65.0,
            "poles": 3,
            "mechanism": "Stored Energy Spring",
            "arc_extinction": "De-ionizing Air Chutes",
        },
        "standards": ["IEC 60947-2", "IEC 62271-100"],
        "tags": ["acb", "low-voltage", "switchgear", "1600a", "65ka"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cb-iec62271-lv-mccb-250a-36ka",
        "type": "breaker",
        "category": "IEC 62271",
        "subcategory": "Molded Case Circuit Breaker",
        "name": "LV Molded Case Circuit Breaker 250A 36kA",
        "manufacturer": "Standard IEC Class",
        "model_number": "MCCB-250-36",
        "specs": {
            "rated_voltage_kv": 0.415,
            "rated_current_a": 250,
            "breaking_capacity_ka": 36.0,
            "making_capacity_ka": 75.6,
            "poles": 3,
            "trip_unit": "Electronic LSI",
        },
        "standards": ["IEC 60947-2"],
        "tags": ["mccb", "low-voltage", "panelboard", "250a", "36ka"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cb-iec62271-mv-vcb-12kv-1250a-25ka",
        "type": "breaker",
        "category": "IEC 62271",
        "subcategory": "Vacuum Circuit Breaker",
        "name": "12kV Vacuum Circuit Breaker 1250A 25kA",
        "manufacturer": "Standard IEC Class",
        "model_number": "VCB-12-1250-25",
        "specs": {
            "rated_voltage_kv": 12.0,
            "rated_current_a": 1250,
            "breaking_capacity_ka": 25.0,
            "making_capacity_ka": 62.5,
            "short_time_withstand_ka_3s": 25.0,
            "operating_sequence": "O-0.3s-CO-3min-CO",
            "medium": "Vacuum",
        },
        "standards": ["IEC 62271-100", "IEC 62271-1"],
        "tags": ["vcb", "medium-voltage", "vacuum", "12kv", "25ka"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cb-iec62271-mv-vcb-24kv-1250a-25ka",
        "type": "breaker",
        "category": "IEC 62271",
        "subcategory": "Vacuum Circuit Breaker",
        "name": "24kV Vacuum Circuit Breaker 1250A 25kA",
        "manufacturer": "Standard IEC Class",
        "model_number": "VCB-24-1250-25",
        "specs": {
            "rated_voltage_kv": 24.0,
            "rated_current_a": 1250,
            "breaking_capacity_ka": 25.0,
            "making_capacity_ka": 62.5,
            "short_time_withstand_ka_3s": 25.0,
            "operating_sequence": "O-0.3s-CO-3min-CO",
            "medium": "Vacuum",
        },
        "standards": ["IEC 62271-100", "IEC 62271-1"],
        "tags": ["vcb", "medium-voltage", "vacuum", "24kv", "25ka"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "cb-iec62271-hv-sf6-72kv-2500a-31ka",
        "type": "breaker",
        "category": "IEC 62271",
        "subcategory": "SF6 Circuit Breaker",
        "name": "72.5kV SF6 Gas Circuit Breaker 2500A 31.5kA",
        "manufacturer": "Standard IEC Class",
        "model_number": "GCB-72.5-2500-31.5",
        "specs": {
            "rated_voltage_kv": 72.5,
            "rated_current_a": 2500,
            "breaking_capacity_ka": 31.5,
            "making_capacity_ka": 78.75,
            "short_time_withstand_ka_3s": 31.5,
            "operating_sequence": "O-0.3s-CO-3min-CO",
            "medium": "SF6 Gas",
        },
        "standards": ["IEC 62271-100", "IEC 62271-102"],
        "tags": ["sf6", "high-voltage", "gas-insulated", "72.5kv", "31.5ka"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
]

TEMPLATES = [
    {
        "id": "template-protection-oc-ef-normal-inverse",
        "type": "template",
        "category": "Protection Coordination",
        "subcategory": "Overcurrent & Earth Fault",
        "name": "Feeder Overcurrent & Earth Fault Protection Template (50/51/51N)",
        "manufacturer": "AhmedETAP Protection Library",
        "model_number": "TPL-OC-EF-NI",
        "specs": {
            "curve_type": "IEC Normal Inverse",
            "phase_overcurrent_51_pickup_pu": 1.1,
            "phase_time_multiplier": 0.15,
            "phase_instantaneous_50_pickup_pu": 6.5,
            "earth_fault_51n_pickup_pu": 0.2,
            "earth_time_multiplier": 0.1,
            "curve_equation": "t = (0.14 / ((I/Is)^0.02 - 1)) * TMS",
        },
        "standards": ["IEC 60255-151", "IEEE C37.112"],
        "tags": ["protection-coordination", "overcurrent", "earth-fault", "iec-curve"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "template-protection-motor-49-50-51-46",
        "type": "template",
        "category": "Protection Coordination",
        "subcategory": "Motor Protection",
        "name": "MV Induction Motor Complete Protection Template (49/50/51/46)",
        "manufacturer": "AhmedETAP Protection Library",
        "model_number": "TPL-MOTOR-PROT",
        "specs": {
            "thermal_overload_49_pickup": 1.05,
            "thermal_time_constant_min": 15.0,
            "locked_rotor_51lr_pickup": 2.5,
            "locked_rotor_delay_sec": 3.0,
            "short_circuit_50_pickup": 8.0,
            "unbalance_negative_sequence_46_pickup": 0.15,
        },
        "standards": ["IEEE 399", "IEEE 242", "IEC 60255"],
        "tags": ["motor-protection", "thermal-overload", "locked-rotor", "negative-sequence"],
        "is_verified": True,
        "source": "iec-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
    {
        "id": "template-protection-transformer-differential-87t",
        "type": "template",
        "category": "Protection Coordination",
        "subcategory": "Transformer Protection",
        "name": "Transformer Biased Differential Protection Template (87T)",
        "manufacturer": "AhmedETAP Protection Library",
        "model_number": "TPL-XFMR-DIFF-87T",
        "specs": {
            "basic_pickup_pu": 0.2,
            "slope_1_percent": 25.0,
            "slope_2_percent": 60.0,
            "breakpoint_1_pu": 1.25,
            "harmonic_restraint_2nd_percent": 15.0,
            "harmonic_restraint_5th_percent": 35.0,
            "unrestrained_instantaneous_pickup_pu": 8.0,
        },
        "standards": ["IEEE C37.91", "IEC 60255"],
        "tags": ["transformer-protection", "differential", "87t", "harmonic-restraint"],
        "is_verified": True,
        "source": "ieee-standard",
        "contributor": "AhmedETAP Standards Committee",
        "created_at": "2026-01-01T00:00:00Z",
        "updated_at": "2026-01-01T00:00:00Z",
    },
]


def write_components():
    # Cables
    cables_dir = BASE_DIR / "cables" / "iec60364"
    cables_dir.mkdir(parents=True, exist_ok=True)
    cable_manifest = []
    for c in CABLES:
        filename = f"{c['id'].replace('cable-iec60364-', '').replace('-', '_')}.json"
        with open(cables_dir / filename, "w", encoding="utf-8") as f:
            json.dump(c, f, indent=2)
        cable_manifest.append(filename)
    with open(cables_dir / "index.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "category": "cables",
                "standard": "IEC 60364",
                "title": "IEC 60364 Standard Low & Medium Voltage Cables",
                "items": cable_manifest,
            },
            f,
            indent=2,
        )

    # Transformers
    xfmr_dir = BASE_DIR / "transformers" / "ieee_c57"
    xfmr_dir.mkdir(parents=True, exist_ok=True)
    xfmr_manifest = []
    for t in TRANSFORMERS:
        filename = f"{t['id'].replace('xfmr-ieee-c57-', '').replace('-', '_')}.json"
        with open(xfmr_dir / filename, "w", encoding="utf-8") as f:
            json.dump(t, f, indent=2)
        xfmr_manifest.append(filename)
    with open(xfmr_dir / "index.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "category": "transformers",
                "standard": "IEEE C57",
                "title": "IEEE C57 Distribution & Power Transformers",
                "items": xfmr_manifest,
            },
            f,
            indent=2,
        )

    # Breakers
    cb_dir = BASE_DIR / "breakers" / "iec62271"
    cb_dir.mkdir(parents=True, exist_ok=True)
    cb_manifest = []
    for b in BREAKERS:
        filename = f"{b['id'].replace('cb-iec62271-', '').replace('-', '_')}.json"
        with open(cb_dir / filename, "w", encoding="utf-8") as f:
            json.dump(b, f, indent=2)
        cb_manifest.append(filename)
    with open(cb_dir / "index.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "category": "breakers",
                "standard": "IEC 62271",
                "title": "IEC 62271 / IEC 60947 Switchgear and Breakers",
                "items": cb_manifest,
            },
            f,
            indent=2,
        )

    # Templates
    tpl_dir = BASE_DIR / "templates"
    tpl_dir.mkdir(parents=True, exist_ok=True)
    tpl_manifest = []
    for t in TEMPLATES:
        filename = f"{t['id'].replace('template-protection-', '').replace('-', '_')}.json"
        with open(tpl_dir / filename, "w", encoding="utf-8") as f:
            json.dump(t, f, indent=2)
        tpl_manifest.append(filename)
    with open(tpl_dir / "index.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "category": "templates",
                "standard": "IEC/IEEE Protection",
                "title": "Protection Coordination Templates",
                "items": tpl_manifest,
            },
            f,
            indent=2,
        )

    print(
        f"Generated {len(CABLES)} cables, {len(TRANSFORMERS)} transformers, {len(BREAKERS)} breakers, {len(TEMPLATES)} templates."
    )


if __name__ == "__main__":
    write_components()
