#!/usr/bin/env python3
"""
Generate a production-ready .env file for the AhmedETAP Platform.

Reads credentials from environment variables (NOT hardcoded) and writes a
complete .env file. The generated .env is gitignored and never committed.

REQUIRED environment variables (export before running):
    ETAP_VERCEL_TOKEN        Vercel access token (vcp_...)
    ETAP_VERCEL_PROJECT_ID   Vercel project ID (prj_...)
    ETAP_HF_TOKEN            Hugging Face access token (hf_...)
    ETAP_HF_SPACE_NAME       HF Space name (user/space)
    ETAP_GITHUB_PAT          GitHub personal access token (for CI/CD sync)

OPTIONAL environment variables (enable additional integrations):
    ETAP_NEO4J_PASSWORD      Neo4j password (graph DB for network topology)
    ETAP_SUPABASE_URL        Supabase project URL (https://xxx.supabase.co)
    ETAP_SUPABASE_ANON_KEY   Supabase publishable/anon key
    ETAP_SUPABASE_SERVICE_KEY  Supabase service-role key
    ETAP_SUPABASE_PAT        Supabase personal access token (ops only)
    ETAP_LANGFUSE_PUBLIC     Langfuse public key (pk-lf-...)
    ETAP_LANGFUSE_SECRET     Langfuse secret key (sk-lf-...)
    ETAP_LANGWATCH_KEY       LangWatch API key (sk-lw-...)
    ETAP_SMITHERY_KEY        Smithery MCP API key
    ETAP_OPENAI_API_KEY      OpenAI API key
    ETAP_ANTHROPIC_API_KEY   Anthropic API key
    ETAP_GOOGLE_API_KEY      Google Gemini API key
    ETAP_GEMINI_API_KEY      Gemini API key (defaults to Google key)

Usage:
    export ETAP_VERCEL_TOKEN=vcp_xxx
    export ETAP_VERCEL_PROJECT_ID=prj_xxx
    export ETAP_HF_TOKEN=hf_xxx
    export ETAP_HF_SPACE_NAME=user/space
    export ETAP_GITHUB_PAT=ghp_xxx
    # Optional:
    export ETAP_NEO4J_PASSWORD=xxx
    export ETAP_SUPABASE_URL=https://xxx.supabase.co
    export ETAP_SUPABASE_ANON_KEY=sb_publishable_xxx
    export ETAP_SUPABASE_SERVICE_KEY=sb_secret_xxx
    export ETAP_LANGFUSE_PUBLIC=pk-lf-xxx
    export ETAP_LANGFUSE_SECRET=sk-lf-xxx
    export ETAP_LANGWATCH_KEY=sk-lw-xxx
    export ETAP_SMITHERY_KEY=xxx
    python scripts/setup_env.py

Security:
- This script contains NO hardcoded secrets
- All secrets are read from the environment at runtime
- The generated .env is written with 0600 permissions and is gitignored
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

try:
    from cryptography.fernet import Fernet
    _HAS_CRYPTO = True
except ImportError:
    _HAS_CRYPTO = False

REQUIRED_VARS = [
    "ETAP_VERCEL_TOKEN",
    "ETAP_VERCEL_PROJECT_ID",
    "ETAP_HF_TOKEN",
    "ETAP_HF_SPACE_NAME",
    "ETAP_GITHUB_PAT",
]

OPTIONAL_VARS = [
    "ETAP_NEO4J_PASSWORD",
    "ETAP_SUPABASE_URL",
    "ETAP_SUPABASE_ANON_KEY",
    "ETAP_SUPABASE_SERVICE_KEY",
    "ETAP_SUPABASE_PAT",
    "ETAP_LANGFUSE_PUBLIC",
    "ETAP_LANGFUSE_SECRET",
    "ETAP_LANGWATCH_KEY",
    "ETAP_SMITHERY_KEY",
    "ETAP_OPENAI_API_KEY",
    "ETAP_ANTHROPIC_API_KEY",
    "ETAP_GOOGLE_API_KEY",
    "ETAP_GEMINI_API_KEY",
    # Additional LLM providers (added 2026-07-07)
    "ETAP_RENDER_API_KEY",
    "ETAP_ZENMUX_API_KEY",
    "ETAP_NVIDIA_API_KEY",
    "ETAP_FIREWORKS_API_KEY",
    "ETAP_GITHUB_MODELS_API_KEY",
    "ETAP_OPENMODEL_API_KEY",
    "ETAP_MODAL_API_KEY",
    # Additional LLM providers (added 2026-07-08)
    "ETAP_BYNARA_API_KEY",
    "ETAP_CLOUDFLARE_API_KEY",
    "ETAP_CLOUDFLARE_ACCOUNT_ID",
]


def _get_or_die(name: str) -> str:
    """Read a required environment variable or exit with a clear error."""
    val = os.environ.get(name, "").strip()
    if not val:
        sys.stderr.write(
            f"ERROR: environment variable '{name}' is not set.\n"
            f"       Export it before running this script. Example:\n"
            f"         export {name}=<your-value>\n"
        )
        sys.exit(2)
    return val


def _get_optional(name: str, default: str = "") -> str:
    """Read an optional environment variable, returning default if unset."""
    return os.environ.get(name, default).strip()


def _env_block(c: dict[str, str]) -> str:
    """Build the full .env file content from a credential dict."""
    # Always use SQLite for local development. Supabase Postgres requires a
    # direct connection string (with real DB password, NOT the service key).
    # The SUPABASE_URL we store is the REST API endpoint, not a DB pooler URL.
    # To switch to Supabase Postgres in production, set DATABASE_URL manually
    # in .env to: postgresql+asyncpg://postgres.PROJECT_REF:DB_PASSWORD@aws-0-pooler.supabase.com:5432/postgres
    database_url = "sqlite+aiosqlite:///./etap.db"

    return f"""# =============================================================================
# AhmedETAP — Production Environment Configuration
# =============================================================================
# Generated by scripts/setup_env.py
# WARNING: Contains real credentials. NEVER commit to version control.
# All 14 engineering modules and 25 AI agents are ACTIVE (no beta, no demo).
# =============================================================================

# =============================================================================
# SECURITY & AUTHENTICATION
# =============================================================================
JWT_SECRET_KEY={c['jwt']}
FERNET_ENCRYPTION_KEY={c['fernet']}
ENCRYPTION_KEY={c['fernet']}
ENVIRONMENT=production
PORT=8000
HOST=0.0.0.0

# =============================================================================
# DATABASE (Supabase Postgres in production; SQLite fallback for local dev)
# =============================================================================
DATABASE_URL={database_url}
POSTGRES_DB=etap_db
POSTGRES_USER=postgres
POSTGRES_PASSWORD={c.get('supabase_service_key', 'etap_secure_password_change_me')}

# =============================================================================
# REDIS CACHE
# =============================================================================
REDIS_URL=redis://localhost:6379/0

# =============================================================================
# HUGGING FACE  (production credentials)
# =============================================================================
HF_TOKEN={c['hf_token']}
HF_SPACE_NAME={c['hf_space']}
HF_REPO_URL=https://huggingface.co/spaces/{c['hf_space']}

# =============================================================================
# VERCEL  (production credentials)
# =============================================================================
VERCEL_ORG_ID=team_etap
VERCEL_PROJECT_ID={c['vercel_project_id']}
VERCEL_TOKEN={c['vercel_token']}

# =============================================================================
# GITHUB  (used for CI/CD sync)
# =============================================================================
GITHUB_REPOSITORY=ahmdelbaz28-ux/ETAP-AI-WORK-
GITHUB_TOKEN={c['github_pat']}
GITHUB_PAT={c['github_pat']}

# =============================================================================
# NEO4J — Graph Database (network topology)
# =============================================================================
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD={c.get('neo4j_password', 'your-strong-neo4j-password-here')}

# =============================================================================
# SUPABASE — Managed PostgreSQL + Storage + Auth  (production credentials)
# =============================================================================
SUPABASE_URL={c.get('supabase_url') or 'https://your-project.supabase.co'}
SUPABASE_ANON_KEY={c.get('supabase_anon', '')}
SUPABASE_SERVICE_ROLE_KEY={c.get('supabase_service', '')}
SUPABASE_AUTH_ENABLED=true
SUPABASE_PAT={c.get('supabase_pat', '')}

# =============================================================================
# LANGFUSE — Prompt management + observability  (production credentials)
# =============================================================================
LANGFUSE_PUBLIC_KEY={c.get('langfuse_public', '')}
LANGFUSE_SECRET_KEY={c.get('langfuse_secret', '')}
LANGFUSE_BASE_URL=https://cloud.langfuse.com
LANGFUSE_DEFAULT_MODEL=gpt-4o
LANGFUSE_OVERRIDE_MODE=false
LANGFUSE_TIMEOUT=5.0
LANGFUSE_MAX_CAPTURE_CHARS=4096
LANGFUSE_SAFETY_PATHS=/api/studies/run,/api/studies/,/api/agents/,/api/scada/,/api/digital-twin/,/api/validation/,/api/context-engine/
LANGFUSE_HTTP_MAX_BODY=4096
LANGFUSE_ALERT_WEBHOOK_URL=
LANGFUSE_ALERT_WEBHOOK_HEADERS={{}}

# =============================================================================
# LANGWATCH — LLM monitoring  (production credentials)
# =============================================================================
LANGWATCH_API_KEY={c.get('langwatch_key', '')}
LANGWATCH_PROJECT=AhmedETAP-Platform
LANGWATCH_ENDPOINT=https://app.langwatch.ai

# =============================================================================
# SMITHERY MCP — Model Context Protocol  (production credentials)
# =============================================================================
SMITHERY_API_KEY={c.get('smithery_key', '')}
SMITHERY_BASE_URL=https://api.smithery.ai

# =============================================================================
# LLM PROVIDERS  (8 providers — OpenAI-compatible chat/completions API)
# =============================================================================
OPENAI_API_KEY={c.get('openai', 'your-openai-api-key-here')}
ANTHROPIC_API_KEY={c.get('anthropic', 'your-anthropic-api-key-here')}
GOOGLE_API_KEY={c.get('google', 'your-google-api-key-here')}
GEMINI_API_KEY={c.get('gemini', 'your-gemini-api-key-here')}
GEMINI_MODEL=gemini-2.0-flash-exp
GEMINI_TIMEOUT=30
GEMINI_MAX_RETRIES=3
ANTHROPIC_VISION_MODEL=claude-3-5-sonnet-20241022
ANTHROPIC_TIMEOUT=30
ANTHROPIC_MAX_RETRIES=3

# Render API (https://render.com)
RENDER_API_KEY={c.get('render', '')}
RENDER_BASE_URL=https://api.render.com/v1
RENDER_MODEL=gpt-4o-mini

# ZenMux (https://zenmux.ai)
ZENMUX_API_KEY={c.get('zenmux', '')}
ZENMUX_BASE_URL=https://api.zenmux.ai/v1
ZENMUX_MODEL=gpt-4o-mini

# NVIDIA NIM (https://build.nvidia.com)
# Note: NVIDIA supports many models including minimaxai/minimax-m3,@cf/meta/llama-3.3-70b-instruct-fp8-fast (multimodal)
NVIDIA_API_KEY={c.get('nvidia', '')}
NVIDIA_BASE_URL=https://integrate.api.nvidia.com/v1
NVIDIA_MODEL=meta/llama-3.1-8b-instruct

# Fireworks AI (https://fireworks.ai)
FIREWORKS_API_KEY={c.get('fireworks', '')}
FIREWORKS_BASE_URL=https://api.fireworks.ai/inference/v1
FIREWORKS_MODEL=accounts/fireworks/models/kimi-k2p7-code

# GitHub Models (https://github.com/marketplace/models)
GITHUB_MODELS_API_KEY={c.get('github_models', '')}
GITHUB_MODELS_BASE_URL=https://models.inference.ai.azure.com/v1
GITHUB_MODELS_MODEL=gpt-4o

# OpenModel (https://openmodel.ai)
OPENMODEL_API_KEY={c.get('openmodel', '')}
OPENMODEL_BASE_URL=https://api.openmodel.ai/v1
OPENMODEL_MODEL=gpt-4o

# Modal (https://modal.com)
MODAL_API_KEY={c.get('modal', '')}
MODAL_BASE_URL=https://api.us-west-2.modal.direct/v1
MODAL_MODEL=zai-org/GLM-5.1-FP8

# Bynara Router (https://bynara.id)
# Note: Bynara offers 25+ models including mimo-v2.5, kimi-k2.7-code-free,
# glm-5.2, gpt-5.4, claude-sonnet-5, mistral-large, deepseek-v4, qwen3.7-max.
# Account requires credits — top up at https://bynara.id
BYNARA_API_KEY={c.get('bynara', '')}
BYNARA_BASE_URL=https://router.bynara.id/v1
BYNARA_MODEL=mimo-v2.5

# Cloudflare Workers AI (https://developers.cloudflare.com/workers-ai/)
# Requires BOTH API token and account ID. Account ID goes in the URL path.
CLOUDFLARE_API_KEY={c.get('cloudflare_api', '')}
CLOUDFLARE_ACCOUNT_ID={c.get('cloudflare_account', '')}
CLOUDFLARE_BASE_URL=https://api.cloudflare.com/client/v4/accounts/PLACEHOLDER/ai/v1
CLOUDFLARE_MODEL=@cf/moonshotai/kimi-k2.6

# Safety-critical LLM guardrails
LLM_MAX_INPUT_CHARS=50000
LLM_ALLOW_UNKNOWN_MODELS=false
LLM_REQUIRE_AGENT_TAG=true
LLM_APPROVED_MODELS=gpt-4o,gpt-4o-mini,gpt-4-turbo,gpt-4.1,gpt-4.1-mini,claude-3-5-sonnet-20241022,claude-3-5-haiku-20241022,claude-3-opus-20240229,gemini-2.0-flash-exp,gemini-1.5-pro,meta/llama-3.1-8b-instruct,abacusai/dracarys-llama-3.1-70b-instruct,accounts/fireworks/models/kimi-k2p7-code,zai-org/GLM-5.1-FP8,mimo-v2.5,@cf/moonshotai/kimi-k2.6,minimaxai/minimax-m3,@cf/meta/llama-3.3-70b-instruct-fp8-fast

# =============================================================================
# ALL 14 ENGINEERING MODULES — FULLY ACTIVE (no beta, no demo)
# =============================================================================
MODULE_ARCFLASH_ENABLED=true
MODULE_MOTORSTARTING_ENABLED=true
MODULE_STABILITY_ENABLED=true
MODULE_CABLE_SIZING_ENABLED=true
MODULE_EARTH_GRID_ENABLED=true
MODULE_RENEWABLE_ENABLED=true
MODULE_BATTERY_STORAGE_ENABLED=true
MODULE_SCADA_ENABLED=true
MODULE_DIGITAL_TWIN_ENABLED=true
MODULE_PREDICTIVE_ENABLED=true
MODULE_ANOMALY_ENABLED=true
MODULE_COORDINATION_ENABLED=true
MODULE_GOAL_PLANNER_ENABLED=true
MODULE_WEATHER_ENABLED=true

# =============================================================================
# ALL 25 AI AGENTS — FULLY ACTIVE (no beta, no demo)
# =============================================================================
AI_AGENTS_ALL_ACTIVE=true
AI_AGENT_ORCHESTRATION_MODE=chief_engineer
AI_AGENT_PROMPT_SOURCE=yaml
AI_AGENT_MAX_PARALLEL=8

# =============================================================================
# FEATURE FLAGS (production — no demo, no preview)
# =============================================================================
PROMETHEUS_ENABLED=true
SIEM_ENABLED=true
SUPABASE_AUTH_ENABLED=true
USE_ETAP=true
ENABLE_ASYNC_EXECUTION=true
ENABLE_CACHING=true
ENABLE_OBSERVABILITY=true

# =============================================================================
# ETAP INTEGRATION (native Windows ETAP bridge)
# =============================================================================
ETAP_HOST=localhost
ETAP_PORT=5000
ETAP_LICENSE_PATH=

# =============================================================================
# OBSERVABILITY
# =============================================================================
PROMETHEUS_PORT=9090
GRAFANA_ADMIN_PASSWORD=etap_grafana_admin_change_me
ENGINEERING_SERVICE_CORS_ORIGINS=http://localhost:3000,https://*.vercel.app

# =============================================================================
# PERFORMANCE TUNING
# =============================================================================
MAX_WORKERS=4
CACHE_SIZE_MB=512
CACHE_DEFAULT_TTL=3600
RATE_LIMIT_MAX=100
RATE_LIMIT_WINDOW=60

# =============================================================================
# TESTING
# =============================================================================
SKIP_LIVE_SCENARIO_TESTS=false

# =============================================================================
# QDRANT — Vector DB (RAG)
# =============================================================================
QDRANT_HOST=localhost
QDRANT_PORT=6333
"""


def _gather_credentials() -> dict[str, str]:
    """Read all required and optional env vars, return credential dict."""
    for v in REQUIRED_VARS:
        _get_or_die(v)

    vercel_token = _get_or_die("ETAP_VERCEL_TOKEN")
    if vercel_token.count("vcp_") > 1:
        second = vercel_token.find("vcp_", 4)
        if second > 0:
            vercel_token = vercel_token[:second]
            sys.stderr.write(f"  Detected double-pasted Vercel token. Trimmed to {len(vercel_token)} chars.\n")

    jwt_secret = secrets.token_hex(32)
    fernet_key = Fernet.generate_key().decode() if _HAS_CRYPTO else secrets.token_urlsafe(44) + "="

    google_key = _get_optional("ETAP_GOOGLE_API_KEY", "")
    gemini_key = _get_optional("ETAP_GEMINI_API_KEY", google_key)

    return {
        "jwt": jwt_secret,
        "fernet": fernet_key,
        "vercel_token": vercel_token,
        "vercel_project_id": _get_or_die("ETAP_VERCEL_PROJECT_ID"),
        "hf_token": _get_or_die("ETAP_HF_TOKEN"),
        "hf_space": _get_or_die("ETAP_HF_SPACE_NAME"),
        "github_pat": _get_or_die("ETAP_GITHUB_PAT"),
        "neo4j_password": _get_optional("ETAP_NEO4J_PASSWORD", ""),
        "supabase_url": _get_optional("ETAP_SUPABASE_URL", ""),
        "supabase_anon": _get_optional("ETAP_SUPABASE_ANON_KEY", ""),
        "supabase_service": _get_optional("ETAP_SUPABASE_SERVICE_KEY", ""),
        "supabase_pat": _get_optional("ETAP_SUPABASE_PAT", ""),
        "langfuse_public": _get_optional("ETAP_LANGFUSE_PUBLIC", ""),
        "langfuse_secret": _get_optional("ETAP_LANGFUSE_SECRET", ""),
        "langwatch_key": _get_optional("ETAP_LANGWATCH_KEY", ""),
        "smithery_key": _get_optional("ETAP_SMITHERY_KEY", ""),
        "openai": _get_optional("ETAP_OPENAI_API_KEY", "your-openai-api-key-here"),
        "anthropic": _get_optional("ETAP_ANTHROPIC_API_KEY", "your-anthropic-api-key-here"),
        "google": google_key or "your-google-api-key-here",
        "gemini": gemini_key or "your-gemini-api-key-here",
        "render": _get_optional("ETAP_RENDER_API_KEY", ""),
        "zenmux": _get_optional("ETAP_ZENMUX_API_KEY", ""),
        "nvidia": _get_optional("ETAP_NVIDIA_API_KEY", ""),
        "fireworks": _get_optional("ETAP_FIREWORKS_API_KEY", ""),
        "github_models": _get_optional("ETAP_GITHUB_MODELS_API_KEY", ""),
        "openmodel": _get_optional("ETAP_OPENMODEL_API_KEY", ""),
        "modal": _get_optional("ETAP_MODAL_API_KEY", ""),
        "bynara": _get_optional("ETAP_BYNARA_API_KEY", ""),
        "cloudflare_api": _get_optional("ETAP_CLOUDFLARE_API_KEY", ""),
        "cloudflare_account": _get_optional("ETAP_CLOUDFLARE_ACCOUNT_ID", ""),
    }


def main() -> int:
    """Read env vars, generate .env file."""
    creds = _gather_credentials()

    env_file = Path("/home/z/my-project/.env")
    if env_file.exists():
        backup = env_file.with_name(".env.bak")
        if backup.exists():
            backup.unlink()
        env_file.rename(backup)
        sys.stderr.write(f"  Backed up existing .env to {backup.name}\n")

    content = _env_block(creds)
    env_file.write_text(content, encoding="utf-8")
    env_file.chmod(0o600)

    # Ensure .env is gitignored
    gitignore = Path("/home/z/my-project/.gitignore")
    if gitignore.exists():
        gi_text = gitignore.read_text(encoding="utf-8")
        if ".env" not in gi_text:
            with gitignore.open("a", encoding="utf-8") as f:
                f.write("\n# Local environment\n.env\n.env.bak\n")
            sys.stderr.write("  Added .env to .gitignore\n")

    print(f"\n  ✓ Wrote {env_file} ({len(content)} bytes)")
    print(f"  ✓ JWT_SECRET_KEY:     {creds['jwt'][:16]}... (truncated)")
    print(f"  ✓ FERNET_KEY:         {creds['fernet'][:16]}... (truncated)")
    print(f"  ✓ VERCEL_TOKEN:       {creds['vercel_token'][:12]}... ({len(creds['vercel_token'])} chars)")
    print(f"  ✓ VERCEL_PROJECT_ID:  {creds['vercel_project_id']}")
    print(f"  ✓ HF_TOKEN:           {creds['hf_token'][:12]}... (truncated)")
    print(f"  ✓ HF_SPACE_NAME:      {creds['hf_space']}")
    print(f"  ✓ GITHUB_PAT:         {creds['github_pat'][:12]}... (truncated)")

    # Optional integrations status
    integrations = [
        ("NEO4J_PASSWORD",   creds["neo4j_password"],  "Neo4j graph DB"),
        ("SUPABASE_URL",     creds["supabase_url"],    "Supabase Postgres"),
        ("SUPABASE_ANON",    creds["supabase_anon"],   "Supabase anon key"),
        ("SUPABASE_SERVICE", creds["supabase_service"],"Supabase service key"),
        ("SUPABASE_PAT",     creds["supabase_pat"],    "Supabase PAT"),
        ("LANGFUSE_PUBLIC",  creds["langfuse_public"], "Langfuse public"),
        ("LANGFUSE_SECRET",  creds["langfuse_secret"], "Langfuse secret"),
        ("LANGWATCH_KEY",    creds["langwatch_key"],   "LangWatch"),
        ("SMITHERY_KEY",     creds["smithery_key"],    "Smithery MCP"),
        ("OPENAI",           creds["openai"],          "OpenAI"),
        ("ANTHROPIC",        creds["anthropic"],       "Anthropic"),
        ("GOOGLE",           creds["google"],          "Google/Gemini"),
        # Additional LLM providers (added 2026-07-07)
        ("RENDER",           creds["render"],          "Render API"),
        ("ZENMUX",           creds["zenmux"],          "ZenMux"),
        ("NVIDIA",           creds["nvidia"],          "NVIDIA NIM"),
        ("FIREWORKS",        creds["fireworks"],       "Fireworks AI"),
        ("GITHUB_MODELS",    creds["github_models"],   "GitHub Models"),
        ("OPENMODEL",        creds["openmodel"],       "OpenModel"),
        ("MODAL",            creds["modal"],           "Modal (GLM-5.1)"),
        # Additional LLM providers (added 2026-07-08)
        ("BYNARA",           creds["bynara"],          "Bynara Router"),
        ("CLOUDFLARE_API",   creds["cloudflare_api"],  "Cloudflare Workers AI"),
        ("CLOUDFLARE_ACCT",  creds["cloudflare_account"], "Cloudflare Account ID"),
    ]
    print("\n  Integration status:")
    for var, val, desc in integrations:
        if val and not val.startswith("your-"):
            print(f"    ✓ {desc:25s}  SET ({val[:10]}...)")
        else:
            print(f"    · {desc:25s}  not set (uses placeholder)")

    print("\n  All 14 modules + 25 AI agents are flagged ACTIVE.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
