#!/usr/bin/env python3
"""
Generate a production-ready .env file for the AhmedETAP Platform.

This script reads credentials from environment variables (NOT hardcoded) and
writes a complete .env file. The generated .env is gitignored and never
committed to source control.

REQUIRED environment variables (export before running):
    ETAP_VERCEL_TOKEN        Vercel access token (vcp_...)
    ETAP_VERCEL_PROJECT_ID   Vercel project ID (prj_...)
    ETAP_HF_TOKEN            Hugging Face access token (hf_...)
    ETAP_HF_SPACE_NAME       HF Space name (user/space)
    ETAP_GITHUB_PAT          GitHub personal access token (for CI/CD sync)

OPTIONAL environment variables:
    ETAP_OPENAI_API_KEY      OpenAI API key
    ETAP_ANTHROPIC_API_KEY   Anthropic API key
    ETAP_GOOGLE_API_KEY      Google Gemini API key
    ETAP_GEMINI_API_KEY      Gemini API key (defaults to Google key)

Usage:
    export ETAP_VERCEL_TOKEN=vcp_xxx
    export ETAP_VERCEL_PROJECT_ID=prj_xxx
    export ETAP_HF_TOKEN=hf_xxx
    export ETAP_HF_SPACE_NAME=user/space
    export ETAP_GITHUB_PAT=ghp_xxx
    python scripts/setup_env.py

Security:
- This script contains NO hardcoded secrets
- All secrets are read from the environment at runtime
- The generated .env is written with 0600 permissions and is gitignored
"""

from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path

try:
    from cryptography.fernet import Fernet
    _HAS_CRYPTO = True
except ImportError:
    _HAS_CRYPTO = False

REQUIRED_VARS = [
    "ETAP_VERCEL_TOKEN",
    "ETAP_VERCEL_PROJECT_ID",
    "ETAP_HF_TOKEN",
    "ETAP_HF_SPACE_NAME",
    "ETAP_GITHUB_PAT",
]

OPTIONAL_VARS = [
    "ETAP_OPENAI_API_KEY",
    "ETAP_ANTHROPIC_API_KEY",
    "ETAP_GOOGLE_API_KEY",
    "ETAP_GEMINI_API_KEY",
]


def _get_or_die(name: str) -> str:
    """Read a required environment variable or exit with a clear error."""
    val = os.environ.get(name, "").strip()
    if not val:
        sys.stderr.write(
            f"ERROR: environment variable '{name}' is not set.\n"
            f"       Export it before running this script. Example:\n"
            f"         export {name}=<your-value>\n"
        )
        sys.exit(2)
    return val


def _get_optional(name: str, default: str = "") -> str:
    """Read an optional environment variable, returning default if unset."""
    return os.environ.get(name, default).strip()


def _env_block(c: dict[str, str]) -> str:
    """Build the full .env file content from a credential dict."""
    return f"""# =============================================================================
# AhmedETAP — Production Environment Configuration
# =============================================================================
# Generated by scripts/setup_env.py
# WARNING: Contains real credentials. NEVER commit to version control.
# =============================================================================

# =============================================================================
# SECURITY & AUTHENTICATION
# =============================================================================
JWT_SECRET_KEY={c['jwt']}
FERNET_ENCRYPTION_KEY={c['fernet']}
ENCRYPTION_KEY={c['fernet']}
ENVIRONMENT=production
PORT=8000
HOST=0.0.0.0

# =============================================================================
# DATABASE
# =============================================================================
DATABASE_URL=sqlite+aiosqlite:///./etap.db
POSTGRES_DB=etap_db
POSTGRES_USER=etap
POSTGRES_PASSWORD=etap_secure_password_change_me

# =============================================================================
# REDIS CACHE
# =============================================================================
REDIS_URL=redis://localhost:6379/0

# =============================================================================
# HUGGING FACE
# =============================================================================
HF_TOKEN={c['hf_token']}
HF_SPACE_NAME={c['hf_space']}
HF_REPO_URL=https://huggingface.co/spaces/{c['hf_space']}

# =============================================================================
# VERCEL
# =============================================================================
VERCEL_ORG_ID=team_etap
VERCEL_PROJECT_ID={c['vercel_project_id']}
VERCEL_TOKEN={c['vercel_token']}

# =============================================================================
# GITHUB  (used for CI/CD sync)
# =============================================================================
GITHUB_REPOSITORY=ahmdelbaz28-ux/ETAP-AI-WORK-
GITHUB_PAT={c['github_pat']}

# =============================================================================
# LLM PROVIDERS
# =============================================================================
OPENAI_API_KEY={c.get('openai', 'your-openai-api-key-here')}
ANTHROPIC_API_KEY={c.get('anthropic', 'your-anthropic-api-key-here')}
GOOGLE_API_KEY={c.get('google', 'your-google-api-key-here')}
GEMINI_API_KEY={c.get('gemini', 'your-gemini-api-key-here')}
GEMINI_MODEL=gemini-2.0-flash-exp
GEMINI_TIMEOUT=30
GEMINI_MAX_RETRIES=3
ANTHROPIC_VISION_MODEL=claude-3-5-sonnet-20241022
ANTHROPIC_TIMEOUT=30
ANTHROPIC_MAX_RETRIES=3

# Safety-critical LLM guardrails
LLM_MAX_INPUT_CHARS=50000
LLM_ALLOW_UNKNOWN_MODELS=false
LLM_REQUIRE_AGENT_TAG=true
LLM_APPROVED_MODELS=gpt-4o,gpt-4o-mini,gpt-4-turbo,gpt-4.1,gpt-4.1-mini,claude-3-5-sonnet-20241022,claude-3-5-haiku-20241022,claude-3-opus-20240229,gemini-2.0-flash-exp,gemini-1.5-pro

# =============================================================================
# ALL 14 ENGINEERING MODULES — FULLY ACTIVE (no beta)
# =============================================================================
# These flags document the production activation status of every engineering
# module. They are read by the engineering service for telemetry dashboards
# and are NOT used to gate execution — every module is always available.
MODULE_ARCFLASH_ENABLED=true
MODULE_MOTORSTARTING_ENABLED=true
MODULE_STABILITY_ENABLED=true
MODULE_CABLE_SIZING_ENABLED=true
MODULE_EARTH_GRID_ENABLED=true
MODULE_RENEWABLE_ENABLED=true
MODULE_BATTERY_STORAGE_ENABLED=true
MODULE_SCADA_ENABLED=true
MODULE_DIGITAL_TWIN_ENABLED=true
MODULE_PREDICTIVE_ENABLED=true
MODULE_ANOMALY_ENABLED=true
MODULE_COORDINATION_ENABLED=true
MODULE_GOAL_PLANNER_ENABLED=true
MODULE_WEATHER_ENABLED=true

# =============================================================================
# ALL 25 AI AGENTS — FULLY ACTIVE (no beta)
# =============================================================================
AI_AGENTS_ALL_ACTIVE=true
AI_AGENT_ORCHESTRATION_MODE=chief_engineer
AI_AGENT_PROMPT_SOURCE=yaml
AI_AGENT_MAX_PARALLEL=8

# =============================================================================
# FEATURE FLAGS (production)
# =============================================================================
PROMETHEUS_ENABLED=true
SIEM_ENABLED=true
SUPABASE_AUTH_ENABLED=false
USE_ETAP=true
ENABLE_ASYNC_EXECUTION=true
ENABLE_CACHING=true
ENABLE_OBSERVABILITY=true

# =============================================================================
# TESTING
# =============================================================================
SKIP_LIVE_SCENARIO_TESTS=false

# =============================================================================
# VECTOR / GRAPH DATABASES (optional)
# =============================================================================
QDRANT_HOST=localhost
QDRANT_PORT=6333
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
"""


def main() -> int:
    """Read env vars, generate .env file."""
    # Validate required inputs
    for v in REQUIRED_VARS:
        _get_or_die(v)

    vercel_token = _get_or_die("ETAP_VERCEL_TOKEN")
    # Auto-trim double-pasted Vercel token (e.g., "vcp_XXXvcp_XXX" → "vcp_XXX")
    if vercel_token.count("vcp_") > 1:
        second = vercel_token.find("vcp_", 4)
        if second > 0:
            vercel_token = vercel_token[:second]
            sys.stderr.write(
                f"  Detected double-pasted Vercel token. Trimmed to {len(vercel_token)} chars.\n"
            )

    # Generate cryptographic secrets
    jwt_secret = secrets.token_hex(32)
    fernet_key = Fernet.generate_key().decode() if _HAS_CRYPTO else secrets.token_urlsafe(44) + "="

    google_key = _get_optional("ETAP_GOOGLE_API_KEY", "")
    gemini_key = _get_optional("ETAP_GEMINI_API_KEY", google_key)

    creds = {
        "jwt": jwt_secret,
        "fernet": fernet_key,
        "vercel_token": vercel_token,
        "vercel_project_id": _get_or_die("ETAP_VERCEL_PROJECT_ID"),
        "hf_token": _get_or_die("ETAP_HF_TOKEN"),
        "hf_space": _get_or_die("ETAP_HF_SPACE_NAME"),
        "github_pat": _get_or_die("ETAP_GITHUB_PAT"),
        "openai": _get_optional("ETAP_OPENAI_API_KEY", "your-openai-api-key-here"),
        "anthropic": _get_optional("ETAP_ANTHROPIC_API_KEY", "your-anthropic-api-key-here"),
        "google": google_key or "your-google-api-key-here",
        "gemini": gemini_key or "your-gemini-api-key-here",
    }

    env_file = Path("/home/z/my-project/.env")
    if env_file.exists():
        backup = env_file.with_name(".env.bak")
        if backup.exists():
            backup.unlink()
        env_file.rename(backup)
        sys.stderr.write(f"  Backed up existing .env to {backup.name}\n")

    content = _env_block(creds)
    env_file.write_text(content, encoding="utf-8")
    env_file.chmod(0o600)

    # Ensure .env is gitignored
    gitignore = Path("/home/z/my-project/.gitignore")
    if gitignore.exists():
        gi_text = gitignore.read_text(encoding="utf-8")
        if ".env" not in gi_text:
            with gitignore.open("a", encoding="utf-8") as f:
                f.write("\n# Local environment\n.env\n.env.bak\n")
            sys.stderr.write("  Added .env to .gitignore\n")

    print(f"\n  ✓ Wrote {env_file} ({len(content)} bytes)")
    print(f"  ✓ JWT_SECRET_KEY: {jwt_secret[:16]}... (truncated)")
    print(f"  ✓ FERNET_KEY:     {fernet_key[:16]}... (truncated)")
    print(f"  ✓ VERCEL_TOKEN:   {vercel_token[:12]}... ({len(vercel_token)} chars)")
    print(f"  ✓ VERCEL_PROJECT_ID: {creds['vercel_project_id']}")
    print(f"  ✓ HF_TOKEN:       {creds['hf_token'][:12]}... (truncated)")
    print(f"  ✓ HF_SPACE_NAME:  {creds['hf_space']}")
    print("\n  All 14 modules + 25 AI agents are flagged ACTIVE in the environment.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
