apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etap-ai.fullname" . }}-secret
  labels:
    {{- include "etap-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.env.ENGINEERING_SERVICE_API_KEY }}
  engineering-service-api-key: {{ .Values.env.ENGINEERING_SERVICE_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.LANGWATCH_API_KEY }}
  langwatch-api-key: {{ .Values.env.LANGWATCH_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.SMITHERY_API_KEY }}
  smithery-api-key: {{ .Values.env.SMITHERY_API_KEY | b64enc | quote }}
  {{- end }}
