"""
api/audit_logs.py — Security Audit Log API endpoint.

Provides a REST API for querying, filtering, and exporting security audit
log entries generated by the :mod:`api.security_audit` module.

Endpoints
---------

* ``GET /``              — List audit logs with search, filter, and pagination
* ``GET /{log_id}``      — Retrieve a single audit log entry by ID
* ``GET /export/csv``    — Export filtered audit logs as CSV
* ``GET /stats``         — Aggregate statistics (count by severity, action, trends)

All endpoints require the ``X-API-Key`` header (validated via
:func:`api.dependencies.get_api_key`).

Pydantic models
---------------

* :class:`AuditLogEntry`       — Single audit log record
* :class:`AuditLogFilter`      — Filter criteria for list queries
* :class:`AuditLogListResponse`— Paginated list response
* :class:`AuditLogExportRequest`— Export request body (future POST support)
"""

from __future__ import annotations

import csv
import io
import math
import uuid
from datetime import UTC, datetime, timedelta
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, ConfigDict, Field

from api.dependencies import get_api_key

# ---------------------------------------------------------------------------
# Duplicated-string-literal constants (python:S1192)
# ---------------------------------------------------------------------------

_DESC_FILTER_SEVERITY = "Filter by severity level"
_DESC_FILTER_ACTION = "Filter by action type"
_DESC_FILTER_USER = "Filter by username"
_DESC_START_DATE = "Start date (ISO-8601)"
_DESC_END_DATE = "End date (ISO-8601)"
_DESC_SEARCH = "Search in details field"

_PATH_AUTH_LOGIN = "/api/v1/auth/login"
_PATH_AUTH_REFRESH = "/api/v1/auth/refresh"
_PATH_AUTH_ROLES = "/api/v1/auth/roles"

_DETAILS_LOGIN_JWT = "Successful login via JWT authentication"
_DETAILS_TOKEN_REFRESHED = "Access token refreshed successfully"

# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------

router = APIRouter(
    prefix="/api/v1/security/audit-logs",
    tags=["security", "audit-logs"],
    dependencies=[Depends(get_api_key)],
)


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class AuditLogEntry(BaseModel):
    """A single security audit log entry.

    Attributes:
        id: Unique identifier for the log entry.
        timestamp: ISO-8601 UTC timestamp when the event occurred.
        severity: Severity level (critical / high / medium / low / info).
        action: The action that was audited (e.g. ``login_success``).
        user: Username or service account that performed the action.
        ip_address: Client IP address associated with the event.
        resource: The resource or endpoint that was accessed.
        details: Free-text description of the event.
        trace_id: Distributed tracing correlation ID.
    """

    model_config = ConfigDict(frozen=True)

    id: str
    timestamp: str
    severity: str
    action: str
    user: str
    ip_address: str
    resource: str
    details: str
    trace_id: str


class AuditLogFilter(BaseModel):
    """Filter criteria for audit log list queries.

    All fields are optional — only provided fields are applied.

    Attributes:
        severity: Filter by severity level.
        action: Filter by action type.
        user: Filter by username.
        start_date: Include entries on or after this ISO-8601 date.
        end_date: Include entries on or before this ISO-8601 date.
        search: Free-text search across the ``details`` field.
    """

    model_config = ConfigDict(frozen=True)

    severity: Optional[str] = Field(default=None, description="Filter by severity level")
    action: Optional[str] = Field(default=None, description="Filter by action type")
    user: Optional[str] = Field(default=None, description="Filter by username")
    start_date: Optional[str] = Field(default=None, description="Start date (ISO-8601)")
    end_date: Optional[str] = Field(default=None, description="End date (ISO-8601)")
    search: Optional[str] = Field(default=None, description="Search in details field")


class AuditLogListResponse(BaseModel):
    """Paginated response for audit log list queries.

    Attributes:
        entries: List of audit log entries for the current page.
        total: Total number of entries matching the filter.
        page: Current page number (1-based).
        page_size: Number of entries per page.
        total_pages: Total number of pages.
    """

    entries: list[AuditLogEntry]
    total: int
    page: int
    page_size: int
    total_pages: int


class AuditLogExportRequest(BaseModel):
    """Request body for audit log export.

    Attributes:
        format: Export format — ``csv`` or ``pdf``.
        filters: Optional filter criteria to apply before exporting.
    """

    format: str = Field(
        default="csv", pattern=r"^(csv|pdf)$", description="Export format: csv or pdf"
    )
    filters: Optional[AuditLogFilter] = Field(default=None, description="Filter criteria")


# ---------------------------------------------------------------------------
# Severity statistics model
# ---------------------------------------------------------------------------


class SeverityCount(BaseModel):
    """Count of audit log entries for a single severity level."""

    severity: str
    count: int


class ActionCount(BaseModel):
    """Count of audit log entries for a single action type."""

    action: str
    count: int


class TrendPoint(BaseModel):
    """A single data point in a recent-trend series."""

    date: str
    count: int


class AuditLogStats(BaseModel):
    """Aggregate statistics for audit logs.

    Attributes:
        total: Total number of entries.
        by_severity: Entry counts grouped by severity level.
        by_action: Entry counts grouped by action type.
        recent_trends: Daily entry counts for the last 7 days.
    """

    total: int
    by_severity: list[SeverityCount]
    by_action: list[ActionCount]
    recent_trends: list[TrendPoint]


# ---------------------------------------------------------------------------
# In-memory sample data (≥ 20 entries for development / demo)
# ---------------------------------------------------------------------------

_NOW = datetime.now(UTC)


def _ts(minutes_ago: int) -> str:
    """Return an ISO-8601 UTC timestamp *minutes_ago* from now."""
    return (_NOW - timedelta(minutes=minutes_ago)).isoformat()


def _tid() -> str:
    """Generate a short trace ID for demo data."""
    return uuid.uuid4().hex[:16]


_SAMPLE_AUDIT_LOGS: list[dict[str, Any]] = [
    {
        "id": "al-001",
        "timestamp": _ts(5),
        "severity": "critical",
        "action": "login_failure",
        "user": "attacker",
        "ip_address": "203.0.113.42",
        "resource": "/api/v1/auth/login",
        "details": "Brute-force login attempt detected — 12 failed attempts in 60 seconds",
        "trace_id": _tid(),
    },
    {
        "id": "al-002",
        "timestamp": _ts(12),
        "severity": "high",
        "action": "permission_denied",
        "user": "jsmith",
        "ip_address": "10.0.0.55",
        "resource": "/api/v1/admin/users",
        "details": "User attempted to access admin user list without sufficient permissions",
        "trace_id": _tid(),
    },
    {
        "id": "al-003",
        "timestamp": _ts(30),
        "severity": "medium",
        "action": "config_change",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/settings",
        "details": "Modified rate-limiting configuration from 100 req/min to 200 req/min",
        "trace_id": _tid(),
    },
    {
        "id": "al-004",
        "timestamp": _ts(45),
        "severity": "info",
        "action": "login_success",
        "user": "alice",
        "ip_address": "10.0.0.22",
        "resource": "/api/v1/auth/login",
        "details": "Successful login via JWT authentication",
        "trace_id": _tid(),
    },
    {
        "id": "al-005",
        "timestamp": _ts(60),
        "severity": "low",
        "action": "token_refresh",
        "user": "alice",
        "ip_address": "10.0.0.22",
        "resource": "/api/v1/auth/refresh",
        "details": "Access token refreshed successfully",
        "trace_id": _tid(),
    },
    {
        "id": "al-006",
        "timestamp": _ts(90),
        "severity": "high",
        "action": "secret_detected",
        "user": "ci-pipeline",
        "ip_address": "10.0.0.100",
        "resource": "/api/v1/security/scan",
        "details": "Hardcoded API key detected in src/config.py line 42",
        "trace_id": _tid(),
    },
    {
        "id": "al-007",
        "timestamp": _ts(120),
        "severity": "critical",
        "action": "data_export",
        "user": "unknown",
        "ip_address": "198.51.100.7",
        "resource": "/api/v1/export",
        "details": "Large data export (2.3 GB) initiated from unrecognized IP address",
        "trace_id": _tid(),
    },
    {
        "id": "al-008",
        "timestamp": _ts(150),
        "severity": "medium",
        "action": "role_change",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/auth/roles",
        "details": "User 'bob' promoted from 'viewer' to 'engineer' role",
        "trace_id": _tid(),
    },
    {
        "id": "al-009",
        "timestamp": _ts(200),
        "severity": "info",
        "action": "login_success",
        "user": "bob",
        "ip_address": "10.0.0.33",
        "resource": "/api/v1/auth/login",
        "details": "Successful login via email OTP",
        "trace_id": _tid(),
    },
    {
        "id": "al-010",
        "timestamp": _ts(250),
        "severity": "low",
        "action": "token_refresh",
        "user": "bob",
        "ip_address": "10.0.0.33",
        "resource": "/api/v1/auth/refresh",
        "details": "Access token refreshed successfully",
        "trace_id": _tid(),
    },
    {
        "id": "al-011",
        "timestamp": _ts(300),
        "severity": "high",
        "action": "cors_violation",
        "user": "system",
        "ip_address": "192.0.2.14",
        "resource": "/api/v1/studies",
        "details": "Request from disallowed origin https://evil.example.com blocked by CORS policy",
        "trace_id": _tid(),
    },
    {
        "id": "al-012",
        "timestamp": _ts(400),
        "severity": "medium",
        "action": "rate_limit_exceeded",
        "user": "jsmith",
        "ip_address": "10.0.0.55",
        "resource": "/api/v1/studies",
        "details": "Rate limit exceeded — 350 requests in 60 seconds (limit: 200)",
        "trace_id": _tid(),
    },
    {
        "id": "al-013",
        "timestamp": _ts(500),
        "severity": "info",
        "action": "login_success",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/auth/login",
        "details": "Successful login via magic link",
        "trace_id": _tid(),
    },
    {
        "id": "al-014",
        "timestamp": _ts(600),
        "severity": "critical",
        "action": "intrusion_attempt",
        "user": "unknown",
        "ip_address": "203.0.113.99",
        "resource": "/api/v1/admin/backup",
        "details": "SQL injection attempt detected in backup endpoint query parameter",
        "trace_id": _tid(),
    },
    {
        "id": "al-015",
        "timestamp": _ts(800),
        "severity": "high",
        "action": "permission_denied",
        "user": "charlie",
        "ip_address": "10.0.0.44",
        "resource": "/api/v1/auth/roles",
        "details": "Viewer role user attempted to create a new role",
        "trace_id": _tid(),
    },
    {
        "id": "al-016",
        "timestamp": _ts(1000),
        "severity": "medium",
        "action": "config_change",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/settings",
        "details": "Enabled MFA requirement for all users",
        "trace_id": _tid(),
    },
    {
        "id": "al-017",
        "timestamp": _ts(1200),
        "severity": "low",
        "action": "token_refresh",
        "user": "alice",
        "ip_address": "10.0.0.22",
        "resource": "/api/v1/auth/refresh",
        "details": "Access token refreshed successfully",
        "trace_id": _tid(),
    },
    {
        "id": "al-018",
        "timestamp": _ts(1500),
        "severity": "info",
        "action": "login_success",
        "user": "diana",
        "ip_address": "10.0.0.55",
        "resource": "/api/v1/auth/login",
        "details": "Successful login via JWT authentication",
        "trace_id": _tid(),
    },
    {
        "id": "al-019",
        "timestamp": _ts(1800),
        "severity": "high",
        "action": "secret_detected",
        "user": "ci-pipeline",
        "ip_address": "10.0.0.100",
        "resource": "/api/v1/security/scan",
        "details": "Exposed .env file detected in public directory — contains database credentials",
        "trace_id": _tid(),
    },
    {
        "id": "al-020",
        "timestamp": _ts(2100),
        "severity": "critical",
        "action": "intrusion_attempt",
        "user": "unknown",
        "ip_address": "198.51.100.23",
        "resource": "/api/v1/auth/login",
        "details": "Credential stuffing attack detected — 500 login attempts in 5 minutes using leaked password list",
        "trace_id": _tid(),
    },
    {
        "id": "al-021",
        "timestamp": _ts(2400),
        "severity": "medium",
        "action": "rate_limit_exceeded",
        "user": "diana",
        "ip_address": "10.0.0.55",
        "resource": "/api/v1/assets",
        "details": "Rate limit exceeded — 250 requests in 60 seconds (limit: 200)",
        "trace_id": _tid(),
    },
    {
        "id": "al-022",
        "timestamp": _ts(2800),
        "severity": "low",
        "action": "token_refresh",
        "user": "charlie",
        "ip_address": "10.0.0.44",
        "resource": "/api/v1/auth/refresh",
        "details": "Access token refreshed successfully",
        "trace_id": _tid(),
    },
    {
        "id": "al-023",
        "timestamp": _ts(3200),
        "severity": "info",
        "action": "login_success",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/auth/login",
        "details": "Successful login via JWT authentication",
        "trace_id": _tid(),
    },
    {
        "id": "al-024",
        "timestamp": _ts(3600),
        "severity": "high",
        "action": "permission_denied",
        "user": "eve",
        "ip_address": "10.0.0.77",
        "resource": "/api/v1/admin/backup",
        "details": "User attempted to trigger database backup without admin role",
        "trace_id": _tid(),
    },
    {
        "id": "al-025",
        "timestamp": _ts(4000),
        "severity": "medium",
        "action": "role_change",
        "user": "admin",
        "ip_address": "10.0.0.1",
        "resource": "/api/v1/auth/roles",
        "details": "User 'eve' demoted from 'engineer' to 'viewer' role due to policy violation",
        "trace_id": _tid(),
    },
]


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _apply_filters(
    entries: list[dict[str, Any]],
    severity: Optional[str] = None,
    action: Optional[str] = None,
    user: Optional[str] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    search: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Apply filter criteria to a list of audit log dicts.

    Args:
        entries: The full list of audit log dictionaries.
        severity: Filter by severity (case-insensitive match).
        action: Filter by action type (case-insensitive match).
        user: Filter by username (case-insensitive partial match).
        start_date: ISO-8601 datetime — include entries >= this timestamp.
        end_date: ISO-8601 datetime — include entries <= this timestamp.
        search: Free-text search across the ``details`` field (case-insensitive).

    Returns:
        Filtered list of audit log dictionaries.
    """
    result = entries

    if severity is not None:
        sev_lower = severity.lower()
        result = [e for e in result if e["severity"].lower() == sev_lower]

    if action is not None:
        act_lower = action.lower()
        result = [e for e in result if e["action"].lower() == act_lower]

    if user is not None:
        user_lower = user.lower()
        result = [e for e in result if user_lower in e["user"].lower()]

    if start_date is not None:
        try:
            start_dt = datetime.fromisoformat(start_date)
        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Invalid start_date format: {start_date!r}. Expected ISO-8601.",
            ) from None
        result = [e for e in result if datetime.fromisoformat(e["timestamp"]) >= start_dt]

    if end_date is not None:
        try:
            end_dt = datetime.fromisoformat(end_date)
        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Invalid end_date format: {end_date!r}. Expected ISO-8601.",
            ) from None
        result = [e for e in result if datetime.fromisoformat(e["timestamp"]) <= end_dt]

    if search is not None:
        search_lower = search.lower()
        result = [e for e in result if search_lower in e["details"].lower()]

    return result


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("/", response_model=AuditLogListResponse, summary="List audit logs")
async def list_audit_logs(
    page: int = Query(default=1, ge=1, description="1-based page number"),
    page_size: int = Query(default=20, ge=1, le=100, description="Items per page"),
    severity: Optional[str] = Query(default=None, description="Filter by severity level"),
    action: Optional[str] = Query(default=None, description="Filter by action type"),
    user: Optional[str] = Query(default=None, description="Filter by username"),
    start_date: Optional[str] = Query(default=None, description="Start date (ISO-8601)"),
    end_date: Optional[str] = Query(default=None, description="End date (ISO-8601)"),
    search: Optional[str] = Query(default=None, description="Search in details field"),
) -> AuditLogListResponse:
    """List audit log entries with search, filter, and pagination support.

    Supports filtering by **severity**, **action**, **user**, **date range**
    (``start_date`` / ``end_date``), and free-text **search** across the
    ``details`` field.

    Results are sorted by timestamp descending (newest first).
    """
    source_logs = _SAMPLE_AUDIT_LOGS
    try:
        from fireai.core.audit_store import AuditStore

        real_events = AuditStore.get_events()
        if real_events:
            source_logs = real_events
    except Exception:
        pass

    filtered = _apply_filters(
        source_logs,
        severity=severity,
        action=action,
        user=user,
        start_date=start_date,
        end_date=end_date,
        search=search,
    )

    total = len(filtered)
    total_pages = max(1, math.ceil(total / page_size))
    offset = (page - 1) * page_size
    page_entries = filtered[offset : offset + page_size]

    return AuditLogListResponse(
        entries=[AuditLogEntry(**e) for e in page_entries],
        total=total,
        page=page,
        page_size=page_size,
        total_pages=total_pages,
    )


@router.get(
    "/export/csv",
    summary="Export audit logs as CSV",
    response_class=StreamingResponse,
)
async def export_audit_logs_csv(
    severity: Optional[str] = Query(default=None, description="Filter by severity level"),
    action: Optional[str] = Query(default=None, description="Filter by action type"),
    user: Optional[str] = Query(default=None, description="Filter by username"),
    start_date: Optional[str] = Query(default=None, description="Start date (ISO-8601)"),
    end_date: Optional[str] = Query(default=None, description="End date (ISO-8601)"),
    search: Optional[str] = Query(default=None, description="Search in details field"),
) -> StreamingResponse:
    """Export filtered audit log entries as a CSV file download.

    Accepts the same filter parameters as the list endpoint.  Returns a
    ``text/csv`` streaming response with a ``Content-Disposition`` header
    so the browser triggers a file download.

    .. note::

        This endpoint MUST be registered before ``/{log_id}`` to avoid
        FastAPI matching ``"export"`` as a path parameter.
    """
    filtered = _apply_filters(
        _SAMPLE_AUDIT_LOGS,
        severity=severity,
        action=action,
        user=user,
        start_date=start_date,
        end_date=end_date,
        search=search,
    )

    output = io.StringIO()
    writer = csv.DictWriter(
        output,
        fieldnames=[
            "id",
            "timestamp",
            "severity",
            "action",
            "user",
            "ip_address",
            "resource",
            "details",
            "trace_id",
        ],
    )
    writer.writeheader()
    for row in filtered:
        writer.writerow(row)

    output.seek(0)
    filename = f"audit-logs-{datetime.now(UTC).strftime('%Y%m%dT%H%M%SZ')}.csv"
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/stats", response_model=AuditLogStats, summary="Get audit log statistics")
async def get_audit_log_stats() -> AuditLogStats:
    """Return aggregate statistics for audit log entries.

    Returns:
        - **total**: Total number of entries.
        - **by_severity**: Entry counts grouped by severity level.
        - **by_action**: Entry counts grouped by action type.
        - **recent_trends**: Daily entry counts for the last 7 days.
    """
    source_logs = _SAMPLE_AUDIT_LOGS
    try:
        from fireai.core.audit_store import AuditStore

        real_events = AuditStore.get_events()
        if real_events:
            source_logs = real_events
    except Exception:
        pass

    # Count by severity
    severity_counts: dict[str, int] = {}
    for entry in source_logs:
        sev = entry.get("severity", "info")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    # Count by action
    action_counts: dict[str, int] = {}
    for entry in source_logs:
        act = entry.get("action", "unknown")
        action_counts[act] = action_counts.get(act, 0) + 1

    # Recent trends — last 7 days
    # For demo data we build a trend from the timestamps present.
    trends: dict[str, int] = {}
    for i in range(7):
        day = (_NOW - timedelta(days=i)).strftime("%Y-%m-%d")
        trends[day] = 0

    for entry in source_logs:
        try:
            day = datetime.fromisoformat(entry["timestamp"]).strftime("%Y-%m-%d")
        except (ValueError, KeyError):
            continue
        if day in trends:
            trends[day] += 1

    # Sort severity counts by a canonical order
    _SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    by_severity = sorted(
        [SeverityCount(severity=k, count=v) for k, v in severity_counts.items()],
        key=lambda x: _SEV_ORDER.get(x.severity, 99),
    )

    # Sort action counts by count descending
    by_action = sorted(
        [ActionCount(action=k, count=v) for k, v in action_counts.items()],
        key=lambda x: x.count,
        reverse=True,
    )

    # Sort trends by date ascending
    recent_trends = sorted(
        [TrendPoint(date=k, count=v) for k, v in trends.items()],
        key=lambda x: x.date,
    )

    return AuditLogStats(
        total=len(_SAMPLE_AUDIT_LOGS),
        by_severity=by_severity,
        by_action=by_action,
        recent_trends=recent_trends,
    )


@router.get(
    "/{log_id}",
    response_model=AuditLogEntry,
    summary="Get a specific audit log entry",
)
async def get_audit_log(log_id: str) -> AuditLogEntry:
    """Retrieve a single audit log entry by its unique ID.

    .. note::

        This endpoint is registered AFTER ``/export/csv`` and ``/stats``
        to avoid FastAPI matching ``"export"`` or ``"stats"`` as a
        ``log_id`` path parameter.

    Raises:
        404: If no entry with the given ``log_id`` exists.
    """
    for entry in _SAMPLE_AUDIT_LOGS:
        if entry["id"] == log_id:
            return AuditLogEntry(**entry)
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Audit log entry '{log_id}' not found.",
    )
